defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm t
      - run:
          name: Check code syntax
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install published
          command: npx published --git-tag

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - test
      - publish:
          context: org-global
          requires:
            - test
